name: System Test - Windows

on: pull_request

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v2
      - name: Build Project
        shell: bash
        run: |
          cd Team41/Code41
          mkdir build
          cd build
          cmake -A x64 ..
          cmake --build . --target unit_testing --config Release
          cmake --build . --target integration_testing --config Release
          cmake --build . --target autotester --config Release
          cd ../..
      - name: Run System Tests
        shell: bash
        run: |
          cd Team41/Code41/build
          ctest -C Release -R autotester --output-on-failure
          cd ../../..